name = "Drill8"
uuid = "18641f14-447b-44e5-980a-0bc5e35389b7"
authors = ["William Manning <manning.w27@gmail.com>"]
version = "0.1.0"

[deps]
Bplus = "c71c5366-3533-40c3-bcf3-6383cd1eb1eb"
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
CSyntax = "ea656a56-6ca6-5dda-bba5-7b6963a5f74c"
FreeType = "b38be410-82b0-50bf-ab77-7b57e271db43"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Bplus = "0.1.2"
julia = "1.9"
